### ISSUE TITLE
[common] basename fails under linux

### ISSUE THREAD

**Issue by immae1** [starkandwayne/bootstrap-kubernetes-demos#11]
hi, 
i used the updated repo and get the following warning outputs :

`bootstrap-kubernetes-demos up --google
basename: zusätzlicher Operand »state/systems/scf“
„basename --help“ liefert weitere Informationen.
basename: zusätzlicher Operand »state/systems/scf“
... snip.... 
`

**Comment by drnic** [comment]
So I can try to find a workaround for `basename`, what OS are you using?

**Comment by immae1** [comment]
i use Linux Mint 19.1 Cinnamon with kernel 4.15.0-20-generic

**Comment by drnic** [comment]
Are you aware of an alternative to `basename` on your OS?

* http://manpages.ubuntu.com/manpages/bionic/man1/basename.1.html

**Comment by immae1** [comment]
do you mean dirname instead of basename? It seems that now the script is working. issue could be closed.
