### ISSUE TITLE
Timeout for knative not long enough (Azure)

### ISSUE THREAD

**Issue by maeddes** [starkandwayne/bootstrap-kubernetes-demos#25]
I just ran the script (Azure version) to play with Knative with the following command `bootstrap-kubernetes-demos up --azure --knative` and noticed one thing:

- The timeout call to validate knative setup `kubectl wait -l app=controller pod --for condition=Ready -n knative-serving --timeout 30s`is too short and the script will exit. It took almost 5 minutes until this pod was up and the condition met

**Comment by drnic** [comment]
Would you like to submit a PR for a larger timeout?

**Comment by maeddes** [comment]
Larger or maybe configurable. In the end the knative env came up fine, so it is not a functional problem. Just indicating an error which isn't really one.

**Comment by drnic** [comment]
It's ok to make the timeout larger to capture all cases.

**Comment by drnic** [comment]
Increased from 30s to 300s
