### ISSUE TITLE
Basename need extra operand in distros like ubuntu

### ISSUE THREAD

**Issue by immae1** [starkandwayne/bootstrap-kubernetes-demos#26]
If i run the boostrap-kubernetes-demos script under linux (in my case linux mint) i get weird outputs like this:

`bootstrap-kubernetes-demos up --az
basename: extra operand 'state/systems/scf'
Try 'basename --help' for more information.
basename: extra operand 'state/systems/scf'
Try 'basename --help' for more information.
basename: extra operand 'state/systems/scf'
Try 'basename --help' for more information.
basename: extra operand 'state/systems/scf'
Try 'basename --help' for more information.
basename: extra operand 'state/systems/scf'
Try 'basename --help' for more information.
basename: extra operand 'state/systems/scf'
Try 'basename --help' for more information.
basename: extra operand 'state/systems/scf'
Try 'basename --help' for more information.
basename: extra operand 'state/systems/scf'
Try 'basename --help' for more information.
basename: extra operand 'state/systems/scf'
Try 'basename --help' for more information.
basename: extra operand 'state/systems/scf'
Try 'basename --help' for more information.
`

you can reproduce this within a docker ubuntu container:
```

$ docker run -it -v $PWD:/tmp/test ubuntu
root@735ba4641c26:/# cd /tmp/test/

root@735ba4641c26:/tmp/test# bootstrap-kubernetes-demos up --az
basename: extra operand 'state/systems/scf'
Try 'basename --help' for more information.
basename: extra operand 'state/systems/scf'
...... 
```

**Comment by drnic** [comment]
@immae1 thanks for making it simple for me to reproduce; fixed now
