### ISSUE TITLE
[scf] helm upgrade stucks on eirini part

### ISSUE THREAD

**Issue by immae1** [starkandwayne/bootstrap-kubernetes-demos#32]
I run: bootstrap-kubernetes-demos up --azure --scf 

CF-Operator is deployed correct:
`--> Using cf-operator-v0.4.2+85.gc6d71da5.tgz
+ helm upgrade --install --wait --namespace scf cf-operator https://cf-operators.s3.amazonaws.com/helm-charts/cf-operator-v0.4.2%2B85.gc6d71da5.tgz --set provider=gke --set operator-webhook-use-service-reference=true
Release "cf-operator" does not exist. Installing it now.
NAME:   cf-operator
`

but then helm stucks on eirini: 
`Install Cloud Foundry/Eirini (scf) for scf.suse.dev
--> Using scf-3.0.0-c656daa.tgz
+ helm upgrade --install --namespace scf scf https://scf-v3.s3.amazonaws.com/scf-3.0.0-c656daa.tgz --set system_domain=scf.suse.dev --set features.eirini.enabled=true

^C
immi@immi-V`
i waited aprox. 15 min and then hitted crtl-c

**Comment by drnic** [comment]
Can you try setting `export HELM_DEBUG=1` and running again, perhaps helm will indicate where/why its getting stuck?

**Comment by drnic** [comment]
I’ll close this for now. Please reopen if necessary.
